name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Website
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }} # IP Address
          key: ${{ secrets.SSH_KEY }} # Public/private key of server
          username: ${{ secrets.SSH_USERNAME }} # Server username
     
          script: |
            cd /home/ben/repos/birthday-website
            git checkout main
            git pull
            cp index.html /var/www/isitbensbirthday.com/public_html/index.html
            sudo /etc/init.d/apache2 restart
